# Request
# TODO(Kevin): Use an input pointcloud
float32 min_x
float32 max_x
float32 min_y
float32 max_y
float32 min_z
float32 max_z
float32 min_2d_x
float32 max_2d_x
float32 min_2d_y
float32 max_2d_y
---
# Result
# The pose of the most center centroid that was found
geometry_msgs/Pose centroid
sensor_msgs/PointCloud2 cropped_pc
bool success
---
# Feedback
std_msgs/String status
